=== useblocks/sphinx-needs/sphinxcontrib/needs/needsfile.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://json-schema.org/draft-07/schema#",
    "title": "needs.json schema",
    "type": "object",
    "properties": {
        "created": {"type": "string"},
        "current_version": {"type": "string"},
        "project": {"type": "string"},
        "versions":  {
            "type": "object",
             "patternProperties": {
                 "^.*$": {
                     "type": "object",
                     "properties": {
                         "created": {"type": "string"},
                         "filters": {"type": "object"},
                         "filters_amount": {"type": "number"},
                         "needs": {
                             "patternProperties": {
                                 "^.*$": {
                                     "type": "object",
                                     "properties": {
                                         "title": {"type": "string"},
                                         "id": {"type": "string"},
                                         "description": {"type": "string"}
                                     }
                                 }
                             }
                         },
                         "needs_amount": {"type": "number"}
                     }
                 }
             },
             "additionalProperties": false
        }
    },
    "required": ["current_version", "project"]
}

=== useblocks/sphinx-needs/tests/doc_test/external_doc/needs_test_small.json
{
    "created": "2021-05-11T13:54:22.331741",
    "current_version": "1.0",
    "project": "needs test docs",
    "versions": {
        "1.0": {
            "created": "2021-05-11T13:54:22.331724",
            "filters": {},
            "filters_amount": 0,
            "needs": {
                "TEST_01": {
                    "avatar": "",
                    "closed_at": "",
                    "completion": "",
                    "created_at": "",
                    "description": "TEST_01",
                    "docname": "index",
                    "duration": "",
                    "external_css": "external_link",
                    "external_url": "file:///home/daniel/workspace/sphinx/sphinxcontrib-needs/tests/doc_test/external_doc/__error__#TEST_01",
                    "full_title": "TEST_01 DESCRIPTION",
                    "id": "TEST_01",
                    "id_complete": "TEST_01",
                    "id_parent": "TEST_01",
                    "id_prefix": "",
                    "is_external": true,
                    "is_need": true,
                    "is_part": false,
                    "layout": null,
                    "links": ["SPEC_1"],
                    "max_amount": "",
                    "max_content_lines": "",
                    "parent_need": null,
                    "parent_needs": [],
                    "parent_needs_back": ["TEST_02"],
                    "parts": {},
                    "post_template": null,
                    "pre_template": null,
                    "query": "",
                    "section_name": "",
                    "sections": [],
                    "service": "",
                    "signature": "",
                    "specific": "",
                    "status": null,
                    "style": null,
                    "tags": [],
                    "template": null,
                    "title": "TEST_01 DESCRIPTION",
                    "type": "impl",
                    "type_name": "Implementation",
                    "updated_at": "",
                    "url": "",
                    "user": ""
                },
                "TEST_02": {
                    "avatar": "",
                    "closed_at": "",
                    "completion": "",
                    "created_at": "",
                    "description": "TEST_02",
                    "docname": "index",
                    "duration": "",
                    "external_css": "external_link",
                    "external_url": "file:///home/daniel/workspace/sphinx/sphinxcontrib-needs/tests/doc_test/external_doc/__error__#TEST_02",
                    "full_title": "TEST_02 DESCRIPTION",
                    "id": "TEST_02",
                    "id_complete": "TEST_02",
                    "id_parent": "TEST_02",
                    "id_prefix": "",
                    "is_external": true,
                    "is_need": true,
                    "is_part": false,
                    "layout": null,
                    "links": [
                        "TEST_01",
                        "REQ_1"
                    ],
                    "max_amount": "",
                    "max_content_lines": "",
                    "parent_need": "TEST_01",
                    "parent_needs": ["TEST_01"],
                    "parent_needs_back": [],
                    "parts": {},
                    "post_template": null,
                    "pre_template": null,
                    "query": "",
                    "section_name": "Heading",
                    "sections": ["Heading", "Sub-heading"],
                    "service": "",
                    "signature": "a signature",
                    "specific": "",
                    "status": "open",
                    "style": null,
                    "tags": [
                        "test_02",
                        "test"
                    ],
                    "template": null,
                    "title": "TEST_02 DESCRIPTION",
                    "type": "req",
                    "type_name": "Requirement",
                    "updated_at": "",
                    "url": "",
                    "user": ""
                },
                "TEST_03": {
                    "avatar": "",
                    "closed_at": "",
                    "completion": "",
                    "created_at": "",
                    "description": "AAA",
                    "docname": "subpage_a/subpage_b/subpage",
                    "duration": "",
                    "external_css": "external_link",
                    "external_url": "file:///home/daniel/workspace/sphinx/sphinxcontrib-needs/tests/doc_test/external_doc/__error__#TEST_03",
                    "full_title": "AAA",
                    "id": "TEST_03",
                    "id_complete": "TEST_03",
                    "id_parent": "TEST_03",
                    "id_prefix": "",
                    "is_external": true,
                    "is_need": true,
                    "is_part": false,
                    "layout": null,
                    "links": [],
                    "max_amount": "",
                    "max_content_lines": "",
                    "parent_need": null,
                    "parent_needs": [],
                    "parent_needs_back": [],
                    "parts": {},
                    "post_template": null,
                    "pre_template": null,
                    "query": "",
                    "section_name": "",
                    "sections": [],
                    "service": "",
                    "signature": "",
                    "specific": "",
                    "status": "open",
                    "style": null,
                    "tags": [],
                    "template": null,
                    "title": "AAA",
                    "type": "ask",
                    "type_name": "Requirement",
                    "updated_at": "",
                    "url": "",
                    "user": ""
                }
            },
            "needs_amount": 3
        }
    }
}

=== useblocks/sphinx-needs/tests/doc_test/doc_needs_warnings/needs_test_small.json
{
    "created": "2017-08-25T21:17:17.640061",
    "current_version": "0.1.33",
    "project": "Sphinx-Needs",
    "versions": {
        "0.1.33": {
            "created": "2017-08-25T21:17:17.640058",
            "needs": {
                "TEST_01": {
                    "description": "TEST_01",
                    "id": "TEST_01",
                    "links": [],
                    "status": null,
                    "tags": [],
                    "title": "TEST_01 DESCRIPTION",
                    "type": "impl",
                    "type_name": "Implementation"
                },
                "TEST_02": {
                    "description": "TEST_02",
                    "id": "TEST_02",
                    "links": [],
                    "status": "open",
                    "tags": ["test_02", "test"],
                    "title": "TEST_02 DESCRIPTION",
                    "type": "test",
                    "type_name": "Test Case"
                },
                "TEST_03": {
                    "description": "AAA",
                    "id": "TEST_03",
                    "links": [],
                    "status": "closed",
                    "tags": [],
                    "title": "AAA",
                    "type": "spec",
                    "type_name": "Specification"
                }
            }
        }
    }
}

=== useblocks/sphinx-needs/docs/examples/needs.json
{
    "created": "2022-05-12T11:17:01.415971",
    "current_version": "0.7",
    "project": "Sphinx-Needs",
    "versions": {
        "0.7": {
            "created": "2022-05-12T11:17:01.415959",
            "filters": {},
            "filters_amount": 0,
            "needs": {
                "test_req": {
                    "amount": "",
                    "another_option": "",
                    "author": "",
                    "avatar": "",
                    "blocks": [],
                    "blocks_back": [],
                    "checks": [],
                    "checks_back": [],
                    "closed_at": "",
                    "comment": "",
                    "completion": "",
                    "config": "",
                    "created_at": "",
                    "description": "A requirement, which needs to be tested",
                    "docname": "directives/need",
                    "duration": "",
                    "ends_with": [],
                    "ends_with_back": [],
                    "external_css": "external_link",
                    "external_url": null,
                    "full_title": "test me",
                    "github": "",
                    "has_dead_links": "",
                    "has_forbidden_dead_links": "",
                    "hidden": "",
                    "hours": "",
                    "id": "test_req",
                    "id_complete": "test_req",
                    "id_parent": "test_req",
                    "id_prefix": "",
                    "image": "",
                    "is_external": false,
                    "is_modified": false,
                    "is_need": true,
                    "is_part": false,
                    "layout": "",
                    "links": [],
                    "max_amount": "",
                    "max_content_lines": "",
                    "modifications": 0,
                    "my_extra_option": "",
                    "parent_need": null,
                    "parent_needs": [],
                    "parent_needs_back": [],
                    "parts": {},
                    "post_template": null,
                    "pre_template": null,
                    "query": "",
                    "section_name": "extra links",
                    "sections": [
                        "extra links",
                        "links",
                        "Options",
                        "need/ req (or any other defined need type)"
                    ],
                    "service": "",
                    "signature": "",
                    "specific": "",
                    "starts_after": [],
                    "starts_after_back": [],
                    "starts_with": [],
                    "starts_with_back": [],
                    "status": null,
                    "style": null,
                    "tags": [],
                    "template": null,
                    "tests": [],
                    "tests_back": [
                        "test_001"
                    ],
                    "title": "test me",
                    "triggers": [],
                    "triggers_back": [],
                    "type": "req",
                    "type_name": "Requirement",
                    "updated_at": "",
                    "url": "",
                    "user": ""
                },
                "xyz_123": {
                    "amount": "",
                    "another_option": "filter_me",
                    "author": "",
                    "avatar": "",
                    "blocks": [],
                    "blocks_back": [],
                    "checks": [],
                    "checks_back": [],
                    "closed_at": "",
                    "comment": "",
                    "completion": "",
                    "config": "",
                    "created_at": "",
                    "description": "Some content",
                    "docname": "configuration",
                    "duration": "",
                    "ends_with": [],
                    "ends_with_back": [],
                    "external_css": "external_link",
                    "external_url": null,
                    "full_title": "My requirement with custom options",
                    "github": "",
                    "has_dead_links": "",
                    "has_forbidden_dead_links": "",
                    "hidden": "",
                    "hours": "",
                    "id": "xyz_123",
                    "id_complete": "xyz_123",
                    "id_parent": "xyz_123",
                    "id_prefix": "",
                    "image": "",
                    "is_external": false,
                    "is_modified": false,
                    "is_need": true,
                    "is_part": false,
                    "layout": "",
                    "links": [],
                    "max_amount": "",
                    "max_content_lines": "",
                    "modifications": 0,
                    "my_extra_option": "A new option",
                    "parent_need": null,
                    "parent_needs": [],
                    "parent_needs_back": [],
                    "parts": {},
                    "post_template": null,
                    "pre_template": null,
                    "query": "",
                    "section_name": "needs_extra_options",
                    "sections": [
                        "needs_extra_options",
                        "Options",
                        "Configuration"
                    ],
                    "service": "",
                    "signature": "",
                    "specific": "",
                    "starts_after": [],
                    "starts_after_back": [],
                    "starts_with": [],
                    "starts_with_back": [],
                    "status": "open",
                    "style": null,
                    "tags": [],
                    "template": null,
                    "tests": [],
                    "tests_back": [],
                    "title": "My requirement with custom options",
                    "triggers": [],
                    "triggers_back": [],
                    "type": "req",
                    "type_name": "Requirement",
                    "updated_at": "",
                    "url": "",
                    "user": ""
                }
            },
            "needs_amount": 2
        }
    }
}

=== useblocks/sphinx-needs/tests/doc_test/doc_needs_external_needs/needs_test_small.json
{
    "created": "2021-05-11T13:54:22.331741",
    "current_version": "1.0",
    "project": "needs test docs",
    "versions": {
        "1.0": {
            "created": "2021-05-11T13:54:22.331724",
            "filters": {},
            "filters_amount": 0,
            "needs": {
                "TEST_01": {
                    "avatar": "",
                    "closed_at": "",
                    "completion": "",
                    "created_at": "",
                    "description": "TEST_01",
                    "docname": "index",
                    "duration": "",
                    "external_css": "external_link",
                    "external_url": "file:///home/daniel/workspace/sphinx/sphinxcontrib-needs/tests/doc_test/external_doc/__error__#TEST_01",
                    "full_title": "TEST_01 DESCRIPTION",
                    "hidden": "",
                    "id": "TEST_01",
                    "id_complete": "TEST_01",
                    "id_parent": "TEST_01",
                    "id_prefix": "",
                    "is_external": true,
                    "is_need": true,
                    "is_part": false,
                    "layout": null,
                    "links": ["SPEC_1"],
                    "max_amount": "",
                    "max_content_lines": "",
                    "parent_need": null,
                    "parent_needs": [],
                    "parent_needs_back": [],
                    "parts": {},
                    "post_template": null,
                    "pre_template": null,
                    "query": "",
                    "section_name": "",
                    "sections": [],
                    "service": "",
                    "signature": "",
                    "specific": "",
                    "status": null,
                    "style": null,
                    "tags": ["ext_test"],
                    "template": null,
                    "title": "TEST_01 DESCRIPTION",
                    "type": "impl",
                    "type_name": "Implementation",
                    "updated_at": "",
                    "url": "",
                    "user": ""
                },
                "TEST_02": {
                    "avatar": "",
                    "closed_at": "",
                    "completion": "",
                    "created_at": "",
                    "description": "TEST_02",
                    "docname": "index",
                    "duration": "",
                    "external_css": "external_link",
                    "external_url": "file:///home/daniel/workspace/sphinx/sphinxcontrib-needs/tests/doc_test/external_doc/__error__#TEST_02",
                    "full_title": "TEST_02 DESCRIPTION",
                    "hidden": "",
                    "id": "TEST_02",
                    "id_complete": "TEST_02",
                    "id_parent": "TEST_02",
                    "id_prefix": "",
                    "is_external": true,
                    "is_need": true,
                    "is_part": false,
                    "layout": null,
                    "links": [
                        "TEST_01"
                    ],
                    "max_amount": "",
                    "max_content_lines": "",
                    "parent_need": null,
                    "parent_needs": [],
                    "parent_needs_back": [],
                    "parts": {},
                    "post_template": null,
                    "pre_template": null,
                    "query": "",
                    "section_name": "",
                    "sections": [],
                    "service": "",
                    "signature": "",
                    "specific": "",
                    "status": "open",
                    "style": null,
                    "tags": ["ext_test"],
                    "template": null,
                    "title": "TEST_02 DESCRIPTION",
                    "type": "impl",
                    "type_name": "Implementation",
                    "updated_at": "",
                    "url": "",
                    "user": ""
                },
                "TEST_03": {
                    "avatar": "",
                    "closed_at": "",
                    "completion": "",
                    "created_at": "",
                    "description": "AAA",
                    "docname": "subpage_a/subpage_b/subpage",
                    "duration": "",
                    "external_css": "external_link",
                    "external_url": "file:///home/daniel/workspace/sphinx/sphinxcontrib-needs/tests/doc_test/external_doc/__error__#TEST_03",
                    "full_title": "AAA",
                    "hidden": "",
                    "id": "TEST_03",
                    "id_complete": "TEST_03",
                    "id_parent": "TEST_03",
                    "id_prefix": "",
                    "is_external": true,
                    "is_need": true,
                    "is_part": false,
                    "layout": null,
                    "links": [],
                    "max_amount": "",
                    "max_content_lines": "",
                    "parent_need": null,
                    "parent_needs": [],
                    "parent_needs_back": [],
                    "parts": {},
                    "post_template": null,
                    "pre_template": null,
                    "query": "",
                    "section_name": "",
                    "sections": [],
                    "service": "",
                    "signature": "",
                    "specific": "",
                    "status": "open",
                    "style": null,
                    "tags": ["ext_test"],
                    "template": null,
                    "title": "AAA",
                    "type": "impl",
                    "type_name": "Implementation",
                    "updated_at": "",
                    "url": "",
                    "user": ""
                }
            },
            "needs_amount": 3
        }
    }
}

=== useblocks/sphinx-needs/tests/test_lsp/doc_example_lsp/_build/needs/needs.json
{
    "created": "2022-05-10T11:20:13.402171",
    "current_version": "",
    "project": "Test Env",
    "versions": {
        "": {
            "created": "2022-05-10T11:20:13.402153",
            "filters": {},
            "filters_amount": 0,
            "needs": {
                "REQ_1": {
                    "avatar": "",
                    "closed_at": "",
                    "completion": "",
                    "created_at": "",
                    "description": "Requirement content",
                    "docname": "index",
                    "duration": "",
                    "external_css": "external_link",
                    "external_url": null,
                    "full_title": "First requirement",
                    "has_dead_links": "",
                    "has_forbidden_dead_links": "",
                    "hidden": "",
                    "id": "REQ_1",
                    "id_prefix": "",
                    "is_external": false,
                    "is_modified": false,
                    "is_need": true,
                    "is_part": false,
                    "layout": "",
                    "links": [],
                    "max_amount": "",
                    "max_content_lines": "",
                    "modifications": 0,
                    "parent_need": null,
                    "parent_needs": [],
                    "parent_needs_back": [],
                    "parts": {},
                    "post_template": null,
                    "pre_template": null,
                    "query": "",
                    "section_name": "Needs",
                    "sections": [
                        "Needs",
                        "Test-Env project"
                    ],
                    "service": "",
                    "signature": "",
                    "specific": "",
                    "status": "open",
                    "style": null,
                    "tags": [],
                    "template": null,
                    "title": "First requirement",
                    "type": "req",
                    "type_name": "Requirement",
                    "updated_at": "",
                    "url": "",
                    "user": ""
                },
                "SPEC_1": {
                    "avatar": "",
                    "closed_at": "",
                    "completion": "",
                    "created_at": "",
                    "description": "Specification content",
                    "docname": "index",
                    "duration": "",
                    "external_css": "external_link",
                    "external_url": null,
                    "full_title": "First specification",
                    "has_dead_links": "",
                    "has_forbidden_dead_links": "",
                    "hidden": "",
                    "id": "SPEC_1",
                    "id_prefix": "",
                    "is_external": false,
                    "is_modified": false,
                    "is_need": true,
                    "is_part": false,
                    "layout": "",
                    "links": [],
                    "max_amount": "",
                    "max_content_lines": "",
                    "modifications": 0,
                    "parent_need": null,
                    "parent_needs": [],
                    "parent_needs_back": [],
                    "parts": {},
                    "post_template": null,
                    "pre_template": null,
                    "query": "",
                    "section_name": "Needs",
                    "sections": [
                        "Needs",
                        "Test-Env project"
                    ],
                    "service": "",
                    "signature": "",
                    "specific": "",
                    "status": "open",
                    "style": null,
                    "tags": [],
                    "template": null,
                    "title": "First specification",
                    "type": "spec",
                    "type_name": "Specification",
                    "updated_at": "",
                    "url": "",
                    "user": ""
                }
            },
            "needs_amount": 2
        }
    }
}
